### ISSUE TITLE
[Client] Customize page 기본 기능 완성

### ISSUE THREAD

**Issue by spirited-hunger** [codestates/cloudi#107]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: making the material customize buttons work

### TODO
1. [x] sequence bar 구현
2. [x] material 버튼 구현
3. [x] holder 버튼 구현
4. [x] text 넣기 구현 

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `week 3`
- Urgency: `High`
