### ISSUE TITLE
[Server] image type response test file 생성

### ISSUE THREAD

**Issue by dankhan102** [codestates/cloudi#125]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 이미지 파일 요청 응답 테스트 코드 작성하기

### TODO
1. [x] 간단한 seeder 파일 생성
2. [x] 응답으로 buffer -> base64 변환해서 전송
3. [x] 테스트용 routes, controllers 파일 작성

### Labels
- Estimated time: `E: 3h`
- Group :  `server`
- Sprint: `week3`
- Urgency: `High`
