### ISSUE TITLE
[Client] Customize page transition

### ISSUE THREAD

**Issue by spirited-hunger** [codestates/cloudi#218]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: customize page transition animation

### TODO
1. [x] motion-framer 모듈 설치
2. [x] animate, exit, initial 효과 넣기
3. [x] useLocation으로 트러블 슈팅

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `week 4`
- Urgency: `Low`
