### ISSUE TITLE
[Client] customize page axios 요청 작업

### ISSUE THREAD

**Issue by spirited-hunger** [codestates/cloudi#236]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: axios requests from customize page

### TODO
1. [x] GET (초기 로딩시 선택옵션, 사진 불러오기)
2. [x] POST (로그인상태에서 장바구니 담기)
3. [x] 데이터 흐름 관리

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `week 5`
- Urgency: `Middle`
