### ISSUE TITLE
[Client] 컴포넌트 페이지 리팩토링

### ISSUE THREAD

**Issue by spirited-hunger** [codestates/cloudi#237]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: decoupling customize components, refactorying

### TODO
1. [ ] Editor 컴포넌트 container component 화
2. [ ] 다른 컴포넌트 presentation component 화
3. [ ] CSS 코드 Styled component 화

### Labels
- Estimated time: `E: 1h`
- Group : `client`
- Sprint: `week 5`
- Urgency: `Low`
