### ISSUE TITLE
[Server] AWS certificate manager, load balancer, route 53 설정

### ISSUE THREAD

**Issue by dankhan102** [codestates/cloudi#38]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: certificate manager, load balancer, route 53 설정하기

### TODO
1. [x] certificate manager로 SSL 설정
2. [x] load balancer로 request 나누기
3. [x] route53으로 호스팅 영역 생성

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `week2`
- Urgency: `Middle`
