### ISSUE TITLE
[SR] 프로젝트 기획 및 범위설정

### ISSUE THREAD

**Issue by spirited-hunger** [codestates/cloudi#4]
### ISSUE
- Group: `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [x] 프로젝트의 구체적 기능 의논
2. [x] 기능 To-do 리스트 작성
3. [x] WIKI 의 Requirements 작성

### Labels
- Estimated time: `E: 3h`
- Group : `sr`
- Sprint: `week 1`
- Urgency: `High`
