### ISSUE TITLE
[Client] Costomize Page 기본 틀 제작

### ISSUE THREAD

**Issue by spirited-hunger** [codestates/cloudi#57]
### ISSUE
- Group:  `client`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [x] git repository upstream, origin 만들기
2. [x] 개발환경 구축 - 핵심 컴포넌트 파일들 생성, 연결
3. [x] customize page에 header, footer 컴포넌트 삽입
4. [x] 큰 태그들로 틀 잡기

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `week 2`
- Urgency: `Middle`
