### ISSUE TITLE
[Client] 기본 일러스트 작업

### ISSUE THREAD

**Issue by spirited-hunger** [codestates/cloudi#58]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: create illustration files for incense sticks and stands

### TODO
1. [x] incense stick illustration 1/1
2. [x] incense stand illustration 1/9
3. [x] export .png files

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `week 2`
- Urgency: `Low`
