### ISSUE TITLE
[Client] App.js, Header.js 라우팅 작업

### ISSUE THREAD

**Issue by spirited-hunger** [codestates/cloudi#85]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: liking routes in header menu bar using <NavLink> tag

### TODO
1. [x] 전체적인 라우팅 (/, /incense, /quiz, /customize, /*)
2. [x] 헤더 메뉴에 링크 달기
3. [x] 해당 메뉴에 들어가면 background 적용

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `week 2`
- Urgency: `Low`
